# .github/workflows/ci.yml
name: Go CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Go environment
      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      # Step 3: Enable Go modules
      - name: Enable Go Modules
        run: go env -w GO111MODULE=on

      # Step 4: Cache Go modules for faster builds
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Step 5: Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Step 6: Run tests
      - name: Run tests
        run: go test ./...

      # Step 7: Build the Go application
      - name: Build Go HTTP server
        run: go build -v .
